name: livart_dbt
version: "1.0.0"
config-version: 2

profile: livart_dbt

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  livart_dbt:
    staging:
      +materialized: view